/*
  # Add is_always_available ingredient flag (fixes Water/Ice always showing missing)

  ## Problem
  Recipes generated by the AI Chef often list "Water" (and occasionally "Ice")
  as an ingredient. Both availability RPCs (check_recipe_cookability,
  get_recipe_ingredient_statuses) resolve every listed ingredient against the
  shared `ingredients` catalog, then require a matching `user_pantry` row with
  enough quantity. Water/Ice were never seeded rows, so the lookup always
  failed and these staples were unconditionally flagged "missing" for every
  user, on every recipe.

  ## Fix
  1. Add `public.ingredients.is_always_available boolean NOT NULL DEFAULT false`
     (naming follows this repo's boolean convention — see
     20260521054053_rename_onboarding_completed_to_has_completed_onboarding.sql).
  2. Seed three staple rows (Water, Tap Water, Ice) with the flag set true.
  3. Update both RPCs so that, immediately after resolving `v_ingredient_id` in
     their per-ingredient loop, an ingredient flagged `is_always_available`
     short-circuits straight to "available" — skipping the unit_conversions and
     ai_pantry_snapshot lookups entirely for that ingredient.

  ## Collision guard
  The app lets users create private, per-user `ingredients` rows for names it
  doesn't recognize (SmartAddBar "add as new ingredient"), and
  `ingredients_name_key` is a GLOBAL UNIQUE(name) constraint — not scoped by
  user_id (20260522215329_add_user_id_to_ingredients_and_unit_conversions.sql).
  A user could already have privately created a row named exactly "Water",
  "Tap Water", or "Ice" before this migration runs. Each seed INSERT below uses
  `ON CONFLICT (name) DO UPDATE SET is_always_available = true, user_id = NULL`
  (not DO NOTHING) so the flag reliably lands and the row is reclaimed as a
  universal/global row regardless of whether it already existed.

  ## Unit conversions — intentionally not added here
  Per this repo's convention (supabase/CLAUDE.md), every preferred_unit should
  have a matching unit_conversions row. We deliberately skip adding
  ingredient-specific rows for these three staples:
    - Water / Tap Water (preferred_unit 'cup', base_unit 'ml') are already
      covered by the existing global fallback row
      (20260415000001_seed_ingredients.sql:860, cup -> 240 -> ml).
    - Ice (preferred_unit 'cup', base_unit 'g') has no matching global
      conversion (the global 'cup' fallback outputs ml, not g), but this is
      harmless: the RPC change below short-circuits before any unit-conversion
      math runs for is_always_available ingredients, and the frontend
      (SmartAddBar) never allows these three to be written to user_pantry in
      the first place, so no other code path exercises this conversion.

  ## Security notes
  Both RPCs are unchanged in every other respect: still SECURITY DEFINER,
  still SET search_path = '', same REVOKE ALL ... FROM public / GRANT EXECUTE
  ... TO authenticated footer.
*/

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. ingredients.is_always_available
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.ingredients
  ADD COLUMN IF NOT EXISTS is_always_available boolean NOT NULL DEFAULT false;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Seed the three staple rows (reclaiming any pre-existing private row of
--    the same name — see collision guard note above).
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO public.ingredients (name, category, base_unit, preferred_unit, is_always_available, user_id)
VALUES ('Water', 'Pantry', 'ml', 'cup', true, NULL)
ON CONFLICT (name) DO UPDATE SET is_always_available = true, user_id = NULL;

INSERT INTO public.ingredients (name, category, base_unit, preferred_unit, is_always_available, user_id)
VALUES ('Tap Water', 'Pantry', 'ml', 'cup', true, NULL)
ON CONFLICT (name) DO UPDATE SET is_always_available = true, user_id = NULL;

INSERT INTO public.ingredients (name, category, base_unit, preferred_unit, is_always_available, user_id)
VALUES ('Ice', 'Pantry', 'g', 'cup', true, NULL)
ON CONFLICT (name) DO UPDATE SET is_always_available = true, user_id = NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. check_recipe_cookability — short-circuit on is_always_available
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.check_recipe_cookability(p_recipe_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id             uuid;
  v_ingredients         jsonb;
  v_ingredient          jsonb;
  v_ingredient_id       uuid;
  v_is_always_available boolean;
  v_effective_unit      text;
  v_conv_factor         numeric;
  v_required_base_qty   numeric;
  v_pantry_qty          numeric;
  v_all_available       boolean := true;
BEGIN
  SELECT user_id, ingredients
  INTO v_user_id, v_ingredients
  FROM public.saved_recipes
  WHERE id = p_recipe_id;

  IF v_user_id IS NULL OR v_user_id != auth.uid() THEN RETURN false; END IF;

  FOR v_ingredient IN SELECT * FROM jsonb_array_elements(v_ingredients)
  LOOP
    -- Resolve ingredient id and preferred_unit.
    SELECT id, preferred_unit
    INTO v_ingredient_id, v_effective_unit
    FROM public.ingredients
    WHERE lower(name) = lower(v_ingredient->>'name')
    LIMIT 1;

    -- Staples (Water, Tap Water, Ice) are always considered available —
    -- short-circuit before touching unit_conversions/ai_pantry_snapshot.
    v_is_always_available := false;
    IF v_ingredient_id IS NOT NULL THEN
      SELECT is_always_available INTO v_is_always_available
      FROM public.ingredients
      WHERE id = v_ingredient_id;
    END IF;

    IF v_is_always_available THEN
      CONTINUE;
    END IF;

    -- If the AI emitted unit = "" use the ingredient's preferred_unit instead.
    IF v_ingredient->>'unit' IS NOT NULL AND trim(v_ingredient->>'unit') != '' THEN
      v_effective_unit := v_ingredient->>'unit';
    END IF;

    -- Ingredient-specific conversion first, then global fallback.
    v_conv_factor := NULL;

    IF v_ingredient_id IS NOT NULL THEN
      SELECT output_value INTO v_conv_factor
      FROM public.unit_conversions
      WHERE ingredient_id = v_ingredient_id AND input_unit = v_effective_unit
      LIMIT 1;
    END IF;

    IF v_conv_factor IS NULL THEN
      SELECT output_value INTO v_conv_factor
      FROM public.unit_conversions
      WHERE ingredient_id IS NULL AND input_unit = v_effective_unit
      LIMIT 1;
    END IF;

    -- Convert the recipe's required quantity to base units.
    v_required_base_qty := CASE
      WHEN v_conv_factor > 0 THEN (v_ingredient->>'quantity')::numeric * v_conv_factor
      ELSE (v_ingredient->>'quantity')::numeric
    END;

    -- raw_weight_or_count in ai_pantry_snapshot equals current_quantity_value (base units).
    SELECT raw_weight_or_count INTO v_pantry_qty
    FROM public.ai_pantry_snapshot
    WHERE lower(name) = lower(v_ingredient->>'name')
    LIMIT 1;

    IF v_pantry_qty IS NULL OR v_pantry_qty < v_required_base_qty THEN
      v_all_available := false;
      EXIT;
    END IF;
  END LOOP;

  RETURN v_all_available;
END;
$$;

REVOKE ALL ON FUNCTION public.check_recipe_cookability(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.check_recipe_cookability(uuid) TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. get_recipe_ingredient_statuses — short-circuit on is_always_available
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_recipe_ingredient_statuses(p_recipe_id uuid)
RETURNS TABLE(ingredient_name text, available boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id             uuid;
  v_ingredients         jsonb;
  v_ingredient          jsonb;
  v_ingredient_id       uuid;
  v_is_always_available boolean;
  v_effective_unit      text;
  v_conv_factor         numeric;
  v_required_base       numeric;
  v_pantry_qty          numeric;
BEGIN
  SELECT user_id, ingredients
  INTO v_user_id, v_ingredients
  FROM public.saved_recipes
  WHERE id = p_recipe_id;

  IF v_user_id IS NULL OR v_user_id != auth.uid() THEN RETURN; END IF;

  FOR v_ingredient IN SELECT * FROM jsonb_array_elements(v_ingredients)
  LOOP
    -- Resolve ingredient id and preferred_unit.
    SELECT id, preferred_unit
    INTO v_ingredient_id, v_effective_unit
    FROM public.ingredients
    WHERE lower(name) = lower(v_ingredient->>'name')
    LIMIT 1;

    -- Staples (Water, Tap Water, Ice) are always considered available —
    -- short-circuit before touching unit_conversions/ai_pantry_snapshot.
    v_is_always_available := false;
    IF v_ingredient_id IS NOT NULL THEN
      SELECT is_always_available INTO v_is_always_available
      FROM public.ingredients
      WHERE id = v_ingredient_id;
    END IF;

    IF v_is_always_available THEN
      ingredient_name := v_ingredient->>'name';
      available       := true;
      RETURN NEXT;
      CONTINUE;
    END IF;

    -- If the AI emitted unit = "" use the ingredient's preferred_unit instead.
    IF v_ingredient->>'unit' IS NOT NULL AND trim(v_ingredient->>'unit') != '' THEN
      v_effective_unit := v_ingredient->>'unit';
    END IF;

    -- Ingredient-specific conversion first, then global fallback.
    v_conv_factor := NULL;

    IF v_ingredient_id IS NOT NULL THEN
      SELECT output_value INTO v_conv_factor
      FROM public.unit_conversions
      WHERE ingredient_id = v_ingredient_id AND input_unit = v_effective_unit
      LIMIT 1;
    END IF;

    IF v_conv_factor IS NULL THEN
      SELECT output_value INTO v_conv_factor
      FROM public.unit_conversions
      WHERE ingredient_id IS NULL AND input_unit = v_effective_unit
      LIMIT 1;
    END IF;

    -- Convert the recipe's required quantity to base units.
    v_required_base := CASE
      WHEN v_conv_factor > 0 THEN (v_ingredient->>'quantity')::numeric * v_conv_factor
      ELSE (v_ingredient->>'quantity')::numeric
    END;

    -- raw_weight_or_count in ai_pantry_snapshot is already in base units.
    SELECT raw_weight_or_count INTO v_pantry_qty
    FROM public.ai_pantry_snapshot
    WHERE lower(name) = lower(v_ingredient->>'name')
    LIMIT 1;

    ingredient_name := v_ingredient->>'name';
    available       := v_pantry_qty IS NOT NULL AND v_pantry_qty >= v_required_base;
    RETURN NEXT;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.get_recipe_ingredient_statuses(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.get_recipe_ingredient_statuses(uuid) TO authenticated;
