/*
  # Create saved_recipes table

  ## Summary
  Adds a new table for users to save recipes generated by the AI Chef. Includes
  support for archiving, and a database function to compute whether a recipe can
  still be cooked based on the user's current pantry.

  ## New Tables

  ### saved_recipes
  Stores AI-generated recipes that users have chosen to bookmark for later.
  - `id` - Primary key
  - `user_id` - Owner (references auth.users)
  - `recipe_name` - Display name of the recipe
  - `description` - One-sentence description from the AI
  - `servings` - Number of servings
  - `ingredients` - JSONB array of { name, quantity, unit } objects
  - `instructions` - JSONB array of instruction strings
  - `is_archived` - Whether the user has archived/hidden the recipe
  - `created_at` - When the recipe was saved
  - `archived_at` - When the recipe was archived (null if not archived)

  ## New Functions

  ### check_recipe_cookability(recipe_id uuid)
  Returns true if all ingredients in the saved recipe have sufficient quantity
  in the user's pantry (via ai_pantry_snapshot view). This is computed live on
  each query rather than stored, so it always reflects the current pantry state.

  ## Security
  - RLS enabled on saved_recipes
  - Users can only SELECT, INSERT, UPDATE, DELETE their own rows
  - The cookability function uses SECURITY DEFINER with a fixed search_path

  ## Notes
  1. Ingredients are stored as JSONB snapshot — the exact quantities suggested
     by the AI at the time of saving. This is intentional: the recipe is a
     historical record, not a live reference to the ingredients master list.
  2. Cookability is computed at read time by matching ingredient names (case-
     insensitive) against ai_pantry_snapshot and comparing base quantities.
  3. A unique constraint on (user_id, recipe_name, created_at) prevents
     exact duplicate saves within the same second.
*/

-- Create the saved_recipes table
CREATE TABLE IF NOT EXISTS saved_recipes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_name text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  servings integer NOT NULL DEFAULT 1,
  ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
  instructions jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz
);

-- Enable Row Level Security
ALTER TABLE saved_recipes ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own saved recipes"
  ON saved_recipes FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own saved recipes"
  ON saved_recipes FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own saved recipes"
  ON saved_recipes FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own saved recipes"
  ON saved_recipes FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Index for fast per-user lookups
CREATE INDEX IF NOT EXISTS saved_recipes_user_id_idx ON saved_recipes(user_id);
CREATE INDEX IF NOT EXISTS saved_recipes_user_archived_idx ON saved_recipes(user_id, is_archived);

/*
  Function: check_recipe_cookability
  
  Iterates over each ingredient in a saved recipe's JSONB ingredients array
  and checks whether the user's pantry (via ai_pantry_snapshot) has a row with
  a matching name and sufficient raw_weight_or_count.

  Because ingredient units from the AI may differ from the pantry's base unit,
  we rely on ai_pantry_snapshot.raw_weight_or_count (already in base units) and
  attempt a simple name-match. If any ingredient name has no matching pantry row,
  or the pantry quantity is zero or null, we consider it missing.

  Returns: boolean — true if all ingredients appear sufficiently stocked.
*/
CREATE OR REPLACE FUNCTION check_recipe_cookability(p_recipe_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_ingredients jsonb;
  v_ingredient jsonb;
  v_pantry_qty numeric;
  v_all_available boolean := true;
BEGIN
  -- Fetch the recipe owner and ingredients
  SELECT user_id, ingredients
  INTO v_user_id, v_ingredients
  FROM saved_recipes
  WHERE id = p_recipe_id;

  -- Ensure the caller owns this recipe
  IF v_user_id IS NULL OR v_user_id != auth.uid() THEN
    RETURN false;
  END IF;

  -- Check each ingredient against the pantry snapshot
  FOR v_ingredient IN SELECT * FROM jsonb_array_elements(v_ingredients)
  LOOP
    SELECT raw_weight_or_count
    INTO v_pantry_qty
    FROM ai_pantry_snapshot
    WHERE user_id = v_user_id
      AND lower(name) = lower(v_ingredient->>'name')
    LIMIT 1;

    IF v_pantry_qty IS NULL OR v_pantry_qty <= 0 THEN
      v_all_available := false;
      EXIT;
    END IF;
  END LOOP;

  RETURN v_all_available;
END;
$$;
